#!/usr/bin/python3
import sys

def tnnum(s):
    try:
        return int(s)
    except:
        return float(s)


ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tnnum(line)

print(ans)
